//Login actions
export const USERNAME_ENTER = 'USERNAME_ENTER';
export const PASSWORD_ENTER = 'PASSWORD_ENTER';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USERS_LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS';
export const USERS_LOGIN_FAILURE = 'USERS_LOGIN_FAILURE';

//local page
export const ATUAL_LOCAL = 'ATUAL_LOCAL';
export const LOCAL_RESPONSE = 'LOCAL_RESPONSE';
export const LOCAL_FIELD_FILL = 'LOCAL_FIELD_FILL';

//create question page
export const ADD_CONTENT_PK = 'ADD_CONTENT_PK';
export const DISCURSIVE_PAGE_LOAD = 'DISCURSIVE_PAGE_LOAD';
export const DIFFICULTY_LEVEL_SELECTED = 'DIFFICULTY_LEVEL_SELECTED';
export const ADD_QUESTION_BODY = 'ADD_QUESTION_BODY';
export const UPDATE_AWNSERS_FIELD = 'UPDATE_AWNSERS_FIELD';