//Login actions
export const USERNAME_ENTER = 'USERNAME_ENTER';
export const PASSWORD_ENTER = 'PASSWORD_ENTER';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USERS_LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS';
export const USERS_LOGIN_FAILURE = 'USERS_LOGIN_FAILURE';

//local page
export const ATUAL_LOCAL = 'ATUAL_LOCAL';
export const LOCAL_RESPONSE = 'LOCAL_RESPONSE';